export interface Student {
    id: string;
    createdAt: string;
    fullName: string;
    gender: string;
    nisn?: string | null;
    kelas?: string | null;
    birthPlace?: string | null;
    birthDate?: string | null; 
    nik?: string | null;
    religion: string;
    address?: string | null;
    rt?: string | null;
    rw?: string | null;
    dusun?: string | null;
    kelurahan?: string | null;
    kecamatan?: string | null;
    postalCode?: string | null;
    residenceType: string;
    transportMode: string;
    phone?: string | null;
    mobilePhone: string;
    fatherName: string;
    fatherBirthYear?: string | null;
    fatherEducation?: string | null;
    fatherOccupation?: string | null;
    fatherIncome?: string | null;
    fatherNik?: string | null;
    motherName: string;
    motherBirthYear?: string | null;
    motherEducation?: string | null;
    motherOccupation?: string | null;
    motherIncome?: string | null;
    motherNik?: string | null;
    guardianName?: string | null;
    guardianBirthYear?: string | null;
    guardianEducation?: string | null;
    guardianOccupation?: string | null;
    guardianIncome?: string | null;
    guardianNik?: string | null;
    kipNumber?: string | null;
    kipName?: string | null;
    kksPkhNumber?: string | null;
    birthCertificateRegNo?: string | null;
    previousSchool?: string | null;
    childOrder?: string | null;
    kkNumber?: string | null;
    weight?: string | null;
    height?: string | null;
    headCircumference?: string | null;
    siblingsCount?: string | null;
}
